---
title: Introduction to Discrete Probability
title_meta: Chapter 1
description: In this chapter, you will learn about the fundamentals of discrete probability.
---
---type:NormalExercise lang:r xp:100 skills:1
## Exercise 1. Probability of cyan
One ball will be drawn at random from a box containing: 3 cyan balls, 5 magenta balls, and 7 yellow balls. What is the probability that the ball will be cyan?

---type:NormalExercise lang:r xp:100 skills:1
## Exercise 2. Probability of cyan - generalized
Write exercise that has coding to calculate this probability in general

---type:NormalExercise lang:r xp:100 skills:1
## Exercise 3. Probability of not cyan
What is the probability that the ball will not be cyan?

---type:NormalExercise lang:r xp:100 skills:1
## Exercise 4. Probability of not cyan - generalized
Write exercise that has coding to calculate this probability in general

---type:NormalExercise lang:r xp:100 skills:1
## Exercise 5. Sampling without replacement
Instead of taking just one draw, consider taking two draws. You take the second draw without returning the first draw to the box. We call this sampling without replacement. What is the probability that the first draw is cyan and that the second draw is not cyan?

---type:NormalExercise lang:r xp:100 skills:1
## Exercise 6. Sampling without replacement - generalized
Write exercise that has coding to calculate this probability in general

---type:NormalExercise lang:r xp:100 skills:1
## Exercise 7. Sampling with replacement
Now repeat the experiment, but this time, after taking the first draw and recording the color, return it back to the box and shake the box. We call this sampling with replacement. What is the probability that the first draw is cyan and that the second draw is not cyan?

---type:NormalExercise lang:r xp:100 skills:1
## Exercise 8. Sampling with replacement - generalized
Write exercise that has coding to calculate this probability in general

---type:MultipleChoiceExercise lang:r xp:50 skills:1
## Exercise 9. Independence
Two events $A$ and $B$ are independent if $\mbox{Pr}(A \mbox{ and } B) = \mbox{Pr}(A) P(B)$. Under which situation are the draws independent?

A. You don't replace the draw. B. You replace the draw. C. Neither D. Both

---type:NormalExercise lang:r xp:100 skills:1
## Exercise 10. Sampling with replacement part 2
Say you’ve drawn 5 balls from the box, with replacement, and all have been yellow. What is the probability that the next one is yellow?

---type:NormalExercise lang:r xp:100 skills:1
## Exercise 11. Sampling with replacement part 2 - generalized
Write exercise that has coding to calculate this probability in general

