---
title: Continuous Probability
title_meta: Chapter 4
description: In this chapter, you will learn about continuous probability.
---

---type:NormalExercise lang:r xp:100 skills:1
## Exercise 1. Distribution of female heights - 1
Assume the distribution of female heights is approximated by a normal distribution with a mean of 64 inches and a standard deviation of 3 inches. If we pick a female at random, what is the probability that she is 5 feet or shorter?
***= solution
`pnorm(5*12, 64, 3)`

---type:NormalExercise lang:r xp:100 skills:1
## Exercise 2. Distribution of female heights - 2
Assume the distribution of female heights is approximated by a normal distribution with a mean of 64 inches and a standard deviation of 3 inches. If we pick a female at random, what is the probability that she is 6 feet or taller?
***= solution
`1 - pnorm(6*12, 64, 3)`

---type:NormalExercise lang:r xp:100 skills:1
## Exercise 3. Distribution of female heights - 3
Assume the distribution of female heights is approximated by a normal distribution with a mean of 64 inches and a standard deviation of 3 inches. If we pick a female at random what is the probability that she is between 61 and 67 inches.
***= solution
`pnorm(67, 64, 3) - pnorm(61, 64, 3)`

---type:NormalExercise lang:r xp:100 skills:1
## Exercise 4. Distribution of female heights - 4
Repeat the previous exercise, but convert everything to centimeters. That is, multiply every height, including the standard deviation, by 2.54. What is the answer now?
***= solution
`pnorm(67*2.54, 64*2.54, 3*2.54) - pnorm(61*2.54, 64*2.54, 3*2.54)`

Notice that the answer to the question does not change when you change units. This makes sense since the answer to the question should not be affected by what units we use. In fact, if you look closely, you notice that 61 and 64 are both 1 SD away from the average. 

---type:NormalExercise lang:r xp:100 skills:1
## Exercise 5. Probability of 1SD from average
Compute the probability that a randomly picked, normally distributed random variable is within 1 SD from the average.
***= solution
`pnorm(1) - pnorm(-1)`

---type:NormalExercise lang:r xp:100 skills:1
## Exercise 6. Random variable

(Convert this to multiple choice)

To see the math that explains why the answers the previous exercises are the same, suppose we have a random variable with expected value $\mu$ and standard error $\sigma$. Suppose we ask the probability of $X$ being smaller or equal to $a$. Remember that, by definition, $a$ is $(a - \mu)/\sigma$ standard deviations $\sigma$ away from the average $\mu$. The probability is:
$$ \mbox{Pr}(X \leq a) $$

Now we subtract $\mu$ to both sides and then divide both sides by $\simga$:

$$ \mbox{Pr}\left(\frac{X-\mu}{\sigma} \leq \frac{a-\mu}{\sigma} \right) $$

The quantity on the right is a standard normal random variable. It has an average of 0 and a standard error of 1. We will call it $Z$:

$$ \mbox{Pr}\left(Z \leq \frac{a-\mu}{\sigma} \right) $$ So, no matter the units, the probability of $X\leq a$ is the same as the probability of a standard normal variable being less than $(a - \mu)/\sigma$. If mu is the average and sigma the standard error, which of the following R code would therefore give us the right answer in every situation:

A. mean(X<=a) B. pnorm((a - mu)/sigma) C. pnorm((a - mu)/sigma, mu, sigma) D. pnorm(a)

---type:NormalExercise lang:r xp:100 skills:1
## Exercise 7. Distribution of male heights
Imagine the distribution of male adults is approximately normal with an expected value of 69 and a standard deviation of 3. How tall is the male in the 99th percentile? Hint: use qnorm.
***= solution
`qnorm(0.99, 69, 3)`

---type:NormalExercise lang:r xp:100 skills:1
## Exercise 8. Distribution of IQ scores
The distribution of IQ scores is approximately normally distributed. The expected value is 100 and the standard deviation is 15. Suppose you want to know the distribution of the smartest person in your school district if 10,000 people are born each in your school district. Run a Monte Carlo simulation with B=1000 generating one million IQ scores and keeping the highest. Make a histogram.

***= solution
```{r}
B <- 1000
smartest <- replicate(B, {
  simulated_data <- rnorm(10^4, 100, 15)
  max(simulated_data)
})
hist(smartest)
```
